name: publish

on:
  - push
  - workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: prepare hatch
        # language=bash
        run: python3.7 -m pip install hatch

      - name: build
        # language=bash
        run: hatch build

      - name: publish
        # language=bash
        run: hatch publish --user '__token__' --auth '${{ secrets.PYPI_PUBLISHING_TOKEN }}'
